namespace CivitaiSharp.Core.Response;

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// RFC 7807 Problem Details response model for parsing structured API error responses.
/// </summary>
/// <remarks>
/// <para>
/// This is an internal type used to deserialize error responses from APIs that
/// follow the RFC 7807 Problem Details specification. The parsed data is converted
/// to the public <see cref="Error"/> record for consumer use.
/// </para>
/// <para>
/// The <see cref="Extensions"/> property captures any custom RFC 7807 extension fields
/// beyond the standard specification. These extensions are intentionally not propagated
/// to the public <see cref="Error"/> record because they are typically server-implementation-specific
/// and not useful for client-side error handling. All standard RFC 7807 fields that are
/// relevant for error handling (type, title, status, detail, instance, errors, traceId)
/// are properly exposed through the <see cref="Error"/> record.
/// </para>
/// <para>
/// See: https://tools.ietf.org/html/rfc7807
/// </para>
/// <para>
/// This type uses init-only properties instead of a positional record to support
/// <see cref="JsonExtensionDataAttribute"/>, which is incompatible with constructor parameters
/// when using System.Text.Json source generation.
/// </para>
/// </remarks>
internal sealed record ApiErrorResponse
{
    /// <summary>A URI reference that identifies the problem type.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>A short, human-readable summary of the problem type.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>The HTTP status code generated by the origin server.</summary>
    [JsonPropertyName("status")]
    public int? Status { get; init; }

    /// <summary>A human-readable explanation specific to this occurrence.</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; init; }

    /// <summary>A URI reference that identifies the specific occurrence.</summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; init; }

    /// <summary>Field-level validation errors (ASP.NET Core extension).</summary>
    [JsonPropertyName("errors")]
    public IReadOnlyDictionary<string, string[]>? Errors { get; init; }

    /// <summary>The trace identifier for correlating with server logs.</summary>
    [JsonPropertyName("traceId")]
    public string? TraceId { get; init; }

    /// <summary>
    /// Contains any additional properties not explicitly modeled in this record.
    /// </summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extensions { get; set; }
}
